image:
  repository: lwplapbs/back
  tag:  "latest"
  pullPolicy: Always


appconfig: |-
  server.port: 8080
  ################### Kafka ##############################
  spring:
    kafka:
      bootstrap-servers:  front-kafka
    datasource.url: jdbc:postgresql://front-postgresql:5432/postgres
    datasource.username: postgres
    datasource.password: Welcome123
  management.server.port: 8081