global:
  postgresql:
    secrets: front-app-postgresql

image:
  repository: lwplapbs/reader
  tag:  "latest"
  pullPolicy: Always

service:
  type: NodePort

appconfig: |-
  server.port: 8080
  ################### Kafka ##############################
  spring:
    datasource.url: jdbc:postgresql://front-app-postgresql:5432/postgres
    datasource.username: postgres
  management.server.port: 8081

